name: NekoX
version: 5.0-ProMax+++
authors: [_Chinese_Player_]
description: 一个融合了NekoC和toNeko功能的猫娘插件
main: org.cneko.nekox.NekoX
api-version: 1.13

commands:
  pat:
    description: 抚摸猫娘
    usage: /<command> <玩家>
    permission: nekox.pat
  lovebite:
    description: 给玩家一个爱的咬痕（猫娘使用）
    usage: /<command> <玩家>
    permission: nekox.lovebite
  earscratch:
    description: 挠猫娘的耳朵
    usage: /<command> <玩家>
    permission: nekox.earscratch
  purr:
    description: 发出呼噜声（猫娘使用）
    usage: /<command>
    permission: nekox.purr
  hiss:
    description: 发出嘶嘶声（猫娘使用）
    usage: /<command> <玩家>
    permission: nekox.hiss
  scratch:
    description: 挠人（猫娘使用）
    usage: /<command> <玩家>
    permission: nekox.scratch
  attention:
    description: 吸引人类的注意（猫娘使用）
    usage: /<command> <玩家>
    permission: nekox.attention
  nightvision:
    description: 获得夜视效果（猫娘使用）
    usage: /<command> [玩家]
    permission: nekox.nightvision
  jumpboost:
    description: 获得跳跃提升效果（猫娘使用）
    usage: /<command> [玩家]
    permission: nekox.jumpboost
  swiftsneak:
    description: 获得迅捷潜行效果（猫娘使用）
    usage: /<command> [玩家]
    permission: nekox.swiftsneak
  health:
    description: 恢复自己和主人的生命值（猫娘使用）
    usage: /<command>
    permission: nekox.health
  myskills:
    description: 查看猫娘的所有技能及其冷却时间
    usage: /<command>
    permission: nekox.myskills
  nekox:
    description: NekoX主命令
    usage: /<command> <reload/version>
    permission: nekox.admin
  nekoxhelp:
    description: 查看NekoX帮助信息
    usage: /<command>
    permission: nekox.help
  nekoset:
    description: 设置/取消设置玩家为猫娘
    usage: /<command> <玩家> <true/false>
    permission: nekox.admin
  owner:
    description: 主人系统命令
    usage: /<command> <add/remove/list/mylist/help> [玩家]
    permission: nekox.owner
  playernotice:
    description: 开启/关闭玩家接近提醒功能（猫娘使用）
    usage: /<command> [on|off]
    permission: nekox.playernotice

permissions:
  nekox.pat:
    default: true
  nekox.lovebite:
    default: true
  nekox.earscratch:
    default: true
  nekox.purr:
    default: true
  nekox.hiss:
    default: true
  nekox.scratch:
    default: true
  nekox.attention:
    default: true
  nekox.nightvision:
    default: true
  nekox.jumpboost:
    default: true
  nekox.swiftsneak:
    default: true
  nekox.health:
    default: true
  nekox.help:
    default: true
  nekox.myskills:
    default: true
  nekox.playernotice:
    default: true
  nekox.admin:
    default: op
    children:
      nekox.help: true
  nekox.owner:
    default: true