name: NekoX
version: 1.0.0
authors: [CNeko]
description: 一个融合了NekoC和toNeko功能的猫娘插件
main: org.cneko.nekox.NekoX
api-version: 1.21

commands:
  pat:
    description: 抚摸猫娘
    usage: /<command> <玩家>
    permission: nekox.pat
  lovebite:
    description: 给猫娘一个爱的咬痕
    usage: /<command> <玩家>
    permission: nekox.lovebite
  earscratch:
    description: 挠猫娘的耳朵
    usage: /<command> <玩家>
    permission: nekox.earscratch
  purr:
    description: 让猫娘发出呼噜声
    usage: /<command>
    permission: nekox.purr
  hiss:
    description: 让猫娘发出嘶嘶声
    usage: /<command> <玩家>
    permission: nekox.hiss
  scratch:
    description: 让猫娘挠人
    usage: /<command> <玩家>
    permission: nekox.scratch
  attention:
    description: 吸引猫娘的注意
    usage: /<command> <玩家>
    permission: nekox.attention
  nightvision:
    description: 获得夜视效果
    usage: /<command> [玩家]
    permission: nekox.nightvision
  jumpboost:
    description: 获得跳跃提升效果
    usage: /<command> [玩家]
    permission: nekox.jumpboost
  swiftsneak:
    description: 获得迅捷潜行效果
    usage: /<command> [玩家]
    permission: nekox.swiftsneak
  nekox:
    description: NekoX主命令
    usage: /<command> <reload/version>
    permission: nekox.admin
  nekoxhelp:
    description: 查看NekoX帮助信息
    usage: /<command>
    permission: nekox.help
  nekoset:
    description: 设置/取消设置玩家为猫娘
    usage: /<command> <玩家> <true/false>
    permission: nekox.admin

permissions:
  nekox.pat:
    default: true
  nekox.lovebite:
    default: true
  nekox.earscratch:
    default: true
  nekox.purr:
    default: true
  nekox.hiss:
    default: true
  nekox.scratch:
    default: true
  nekox.attention:
    default: true
  nekox.nightvision:
    default: true
  nekox.jumpboost:
    default: true
  nekox.swiftsneak:
    default: true
  nekox.help:
    default: true
  nekox.admin:
    default: op
    children:
      nekox.help: true